[pytest]
testpaths = tests
norecursedirs =
    .git
    .pytest_cache
    .runtime_deps
    .venv
    download
    github-package
    __pycache__
filterwarnings =
    ignore:pkg_resources is deprecated as an API.*:UserWarning:ctranslate2
