"""Import or merge the bundled Wuthering Waves glossary."""
import sqlite3, os, sys
from pathlib import Path

# 确保在项目根目录下运行
script_dir = Path(__file__).resolve().parent
project_dir = script_dir.parents[1]
os.chdir(project_dir)

db_path = os.path.join(project_dir, 'data', 'glossary.db')
print(f'数据库路径: {db_path}')
os.makedirs(os.path.dirname(db_path), exist_ok=True)
merge_mode = "--merge" in sys.argv[1:]
if os.path.exists(db_path) and not merge_mode:
    os.remove(db_path)

conn = sqlite3.connect(db_path)
conn.execute('''CREATE TABLE IF NOT EXISTS glossary (english TEXT NOT NULL, chinese TEXT NOT NULL, game TEXT NOT NULL DEFAULT 'wuwa', category TEXT DEFAULT '', PRIMARY KEY (english, game))''')
conn.execute('CREATE INDEX IF NOT EXISTS idx_game ON glossary(game)')
conn.execute('CREATE INDEX IF NOT EXISTS idx_category ON glossary(category)')

terms = [
    # Current playable roster. English spellings follow the global client;
    # Chinese spellings follow the Simplified Chinese client.
    ("Sanhua", "散华", "wuwa", "character"),
    ("Baizhi", "白芷", "wuwa", "character"),
    ("Lingyang", "凌阳", "wuwa", "character"),
    ("Zhezhi", "折枝", "wuwa", "character"),
    ("Youhu", "釉瑚", "wuwa", "character"),
    ("Carlotta", "珂莱塔", "wuwa", "character"),
    ("Lucilla", "洛瑟菈", "wuwa", "character"),
    ("Hiyuki", "绯雪", "wuwa", "character"),
    ("Suisui", "穗穗", "wuwa", "character"),
    ("Chixia", "炽霞", "wuwa", "character"),
    ("Encore", "安可", "wuwa", "character"),
    ("Mortefi", "莫特斐", "wuwa", "character"),
    ("Changli", "长离", "wuwa", "character"),
    ("Brant", "布兰特", "wuwa", "character"),
    ("Lupa", "露帕", "wuwa", "character"),
    ("Galbrena", "嘉贝莉娜", "wuwa", "character"),
    ("Mornye", "莫宁", "wuwa", "character"),
    ("Aemeath", "爱弥斯", "wuwa", "character"),
    ("Denia", "达妮娅", "wuwa", "character"),
    ("Calcharo", "卡卡罗", "wuwa", "character"),
    ("Yinlin", "吟霖", "wuwa", "character"),
    ("Yuanwu", "渊武", "wuwa", "character"),
    ("Xiangli Yao", "相里要", "wuwa", "character"),
    ("Lumi", "灯灯", "wuwa", "character"),
    ("Augusta", "奥古斯塔", "wuwa", "character"),
    ("Buling", "卜灵", "wuwa", "character"),
    ("Rebecca", "丽贝卡", "wuwa", "character"),
    ("Rover (Electro)", "漂泊者·导电", "wuwa", "character"),
    ("Yangyang", "秧秧", "wuwa", "character"),
    ("Aalto", "秋水", "wuwa", "character"),
    ("Jiyan", "忌炎", "wuwa", "character"),
    ("Jianxin", "鉴心", "wuwa", "character"),
    ("Ciaccona", "夏空", "wuwa", "character"),
    ("Rover (Aero)", "漂泊者·气动", "wuwa", "character"),
    ("Cartethyia", "卡提希娅", "wuwa", "character"),
    ("Iuno", "尤诺", "wuwa", "character"),
    ("Qiuyuan", "仇远", "wuwa", "character"),
    ("Sigrika", "西格莉卡", "wuwa", "character"),
    ("Verina", "维里奈", "wuwa", "character"),
    ("Rover (Spectro)", "漂泊者·衍射", "wuwa", "character"),
    ("Jinhsi", "今汐", "wuwa", "character"),
    ("The Shorekeeper", "守岸人", "wuwa", "character"),
    ("Phoebe", "菲比", "wuwa", "character"),
    ("Zani", "赞妮", "wuwa", "character"),
    ("Lynae", "琳奈", "wuwa", "character"),
    ("Luuk Herssen", "陆·赫斯", "wuwa", "character"),
    ("Lucy", "露西", "wuwa", "character"),
    ("Taoqi", "桃祈", "wuwa", "character"),
    ("Danjin", "丹瑾", "wuwa", "character"),
    ("Camellya", "椿", "wuwa", "character"),
    ("Rover (Havoc)", "漂泊者·湮灭", "wuwa", "character"),
    ("Roccia", "洛可可", "wuwa", "character"),
    ("Cantarella", "坎特蕾拉", "wuwa", "character"),
    ("Phrolova", "弗洛洛", "wuwa", "character"),
    ("Chisa", "千咲", "wuwa", "character"),
    ("Yangyang: Xuanling", "秧秧·玄翎", "wuwa", "character"),

    # Generic/ASR-facing names and named story characters are retained, but
    # kept outside the playable roster category for easier auditing.
    ("Rover", "漂泊者", "wuwa", "character_alias"),
    ("Abby", "阿布", "wuwa", "story_character"),
    ("Geshu Lin", "哥舒临", "wuwa", "story_character"),
    ("Violet", "薇尔莉特", "wuwa", "external_character"),
    # Officially revealed Mengzhou Resonators (3.6–3.7).
    ("Qingxiao", "清宵", "wuwa", "character"),
    ("Jingran", "景燃", "wuwa", "character"),
    ("Suoming", "锁暝", "wuwa", "character"),
    ("Hsin", "心", "wuwa", "character"),
    ("Xin", "心", "wuwa", "character_alias"),
    ("Scar", "伤痕", "wuwa", "story_character"),
    ("Cristoforo", "克里斯托弗", "wuwa", "story_character"),
    ("Schwarzloch", "斯瓦茨洛", "wuwa", "story_character"),
    ("Fleurdelys", "芙露德莉斯", "wuwa", "story_character"),
    ("Hecate", "赫卡忒", "wuwa", "story_character"),
    ("Lorelei", "罗蕾莱", "wuwa", "story_character"),
    ("Leviathan", "利维亚坦", "wuwa", "story_character"),
    ("Resonator", "共鸣者", "wuwa", "system"),
    ("Echo", "声骸", "wuwa", "system"),
    ("Remnant", "回响", "wuwa", "system"),
    ("Lament", "悲鸣", "wuwa", "system"),
    ("Waveworn Phenomenon", "海蚀现象", "wuwa", "system"),
    ("Tacet Field", "无音区", "wuwa", "location"),
    ("Tacet Discord", "残象", "wuwa", "enemy"),
    ("Convene", "唤取", "wuwa", "system"),
    ("Astrite", "星声", "wuwa", "currency"),
    ("Sonance Casket", "声匣", "wuwa", "item"),
    ("Tacet Mark", "声痕", "wuwa", "system"),
    ("Resonance", "共鸣", "wuwa", "system"),
    ("Attribute", "属性", "wuwa", "system"),
    ("Glacio", "冷凝", "wuwa", "element"),
    ("Fusion", "热熔", "wuwa", "element"),
    ("Electro", "导电", "wuwa", "element"),
    ("Aero", "气动", "wuwa", "element"),
    ("Spectro", "衍射", "wuwa", "element"),
    ("Havoc", "湮灭", "wuwa", "element"),
    ("Sentinel", "岁主", "wuwa", "lore"),
    ("Threnodian", "鸣式", "wuwa", "lore"),
    ("Resonance Skill", "共鸣技能", "wuwa", "combat"),
    ("Resonance Liberation", "共鸣解放", "wuwa", "combat"),
    ("Basic Attack", "普攻", "wuwa", "combat"),
    ("Heavy Attack", "重击", "wuwa", "combat"),
    ("Dodge", "闪避", "wuwa", "combat"),
    ("Outburst", "协奏", "wuwa", "combat"),
    ("Harmony", "和声", "wuwa", "combat"),
    ("Weapon", "武器", "wuwa", "system"),
    ("Rectifier", "音感仪", "wuwa", "weapon"),
    ("Blade", "长刃", "wuwa", "weapon"),
    ("Gauntlets", "臂铠", "wuwa", "weapon"),
    ("Sword", "迅刀", "wuwa", "weapon"),
    ("Broadblade", "重剑", "wuwa", "weapon"),
    ("Pistol", "佩枪", "wuwa", "weapon"),
    ("Air Attack", "空中普攻", "wuwa", "combat"),
    ("Aerial Heavy Attack", "空中重击", "wuwa", "combat"),
    ("Dash Attack", "冲刺攻击", "wuwa", "combat"),
    ("Counter Attack", "弹反击杀", "wuwa", "combat"),
    ("Perfect Parry", "完美弹反", "wuwa", "combat"),
    ("Evasion Counter", "闪避反击", "wuwa", "combat"),
    ("Chain Outburst", "连锁协奏", "wuwa", "combat"),
    ("Resonance Chain", "共鸣连锁", "wuwa", "combat"),
    ("Ultimate", "大招", "wuwa", "combat"),
    ("Burst Animation", "大招动画", "wuwa", "combat"),
    ("Invincibility Window", "无敌时长", "wuwa", "combat"),
    ("Stagger", "削韧", "wuwa", "combat"),
    ("Stun", "眩晕", "wuwa", "combat"),
    ("Freeze", "冻结", "wuwa", "combat"),
    ("Burn", "灼烧", "wuwa", "combat"),
    ("Electro Shock", "感电", "wuwa", "combat"),
    ("Slow", "减速", "wuwa", "combat"),
    ("Pull", "聚怪", "wuwa", "combat"),
    ("Knockback", "击退", "wuwa", "combat"),
    ("Launch", "击飞", "wuwa", "combat"),
    ("CD", "冷却时间", "wuwa", "combat"),
    ("CD Reduction", "冷却缩减", "wuwa", "combat"),
    ("Main Stat", "主词条", "wuwa", "echo"),
    ("Sub Stat", "副词条", "wuwa", "echo"),
    ("Flat ATK", "固定攻击", "wuwa", "echo"),
    ("ATK%", "攻击百分比", "wuwa", "echo"),
    ("HP%", "生命值百分比", "wuwa", "echo"),
    ("DEF%", "防御百分比", "wuwa", "echo"),
    ("Element DMG Bonus", "属性伤害加成", "wuwa", "echo"),
    ("Element Mastery", "元素精通", "wuwa", "echo"),
    ("Energy Cost", "cost值", "wuwa", "echo"),
    ("Echo Set", "声骸套装", "wuwa", "echo"),
    ("2-Piece Set", "二件套效果", "wuwa", "echo"),
    ("4-Piece Set", "四件套效果", "wuwa", "echo"),
    ("Echo Skill", "声骸技能", "wuwa", "echo"),
    ("Tier", "声骸品级", "wuwa", "echo"),
    ("Purify", "洗声骸", "wuwa", "echo"),
    ("Reroll Substats", "副词条重刷", "wuwa", "echo"),
    ("Level", "等级", "wuwa", "progression"),
    ("Ascension", "突破", "wuwa", "progression"),
    ("Ascension Material", "突破材料", "wuwa", "progression"),
    ("Skill Levelup", "技能升级", "wuwa", "progression"),
    ("Skill Trace", "技能天赋", "wuwa", "progression"),
    ("Weapon Refine", "武器精炼", "wuwa", "progression"),
    ("Weapon Ascend", "武器突破", "wuwa", "progression"),
    ("EXP", "经验", "wuwa", "progression"),
    ("Resonance Tree", "共鸣树", "wuwa", "progression"),
    ("Resonance Potency", "共鸣效能", "wuwa", "progression"),
    ("Resonance Rate", "共鸣效率", "wuwa", "progression"),
    ("Stamina", "体力", "wuwa", "progression"),
    ("Stamina Cap", "体力上限", "wuwa", "progression"),
    ("Daily Commission", "每日委托", "wuwa", "progression"),
    ("Weekly Boss", "周本BOSS", "wuwa", "progression"),
    ("Domain", "副本", "wuwa", "progression"),
    ("Resource Node", "资源采集点", "wuwa", "progression"),
    ("Inventory", "背包", "wuwa", "progression"),
    ("Storage", "仓库", "wuwa", "progression"),
    ("Craft", "锻造", "wuwa", "progression"),
    ("DPS", "输出", "wuwa", "meta"),
    ("Main DPS", "主C", "wuwa", "meta"),
    ("Sub DPS", "副C", "wuwa", "meta"),
    ("Support", "辅助", "wuwa", "meta"),
    ("Healer", "奶妈", "wuwa", "meta"),
    ("Tank", "坦克", "wuwa", "meta"),
    ("Meta", "版本答案", "wuwa", "meta"),
    ("Build", "配装", "wuwa", "meta"),
    ("Kit", "技能组", "wuwa", "meta"),
    ("Damage", "伤害", "wuwa", "meta"),
    ("Crit Rate", "暴击率", "wuwa", "meta"),
    ("Crit DMG", "暴击伤害", "wuwa", "meta"),
    ("Energy Recharge", "能量回复", "wuwa", "meta"),
    ("Attack Speed", "攻速", "wuwa", "meta"),
    ("Mob", "小怪", "wuwa", "meta"),
    ("Boss", "BOSS", "wuwa", "meta"),
    ("Phase", "阶段", "wuwa", "meta"),
    ("Mechanic", "机制", "wuwa", "meta"),
    ("One shot", "秒了", "wuwa", "meta"),
    ("Rotation", "循环", "wuwa", "meta"),
    ("Combo", "连招", "wuwa", "meta"),
    ("Buff", "增益", "wuwa", "meta"),
    ("Debuff", "减益", "wuwa", "meta"),
    ("CC", "控制", "wuwa", "meta"),
    ("Shield", "盾", "wuwa", "meta"),
    ("Heal", "治疗", "wuwa", "meta"),
    ("Aggro", "仇恨", "wuwa", "meta"),
    ("I-frames", "无敌帧", "wuwa", "meta"),
    ("ER", "能量回复", "wuwa", "meta"),
    ("DMG Multiplier", "伤害乘区", "wuwa", "meta"),
    ("Flat Damage", "固定伤害", "wuwa", "meta"),
    ("Stack", "叠层", "wuwa", "meta"),
    ("Max Stack", "满层", "wuwa", "meta"),
    ("Window", "输出窗口期", "wuwa", "meta"),
    ("Field Time", "驻场时间", "wuwa", "meta"),
    ("Off-field", "后台输出", "wuwa", "meta"),
    ("On-field", "前台站场", "wuwa", "meta"),
    ("Quick Swap", "速切", "wuwa", "meta"),
    ("Rotation Order", "输出轴", "wuwa", "meta"),
    ("Burst Rotation", "大招循环", "wuwa", "meta"),
    ("Single Target", "单体伤害", "wuwa", "meta"),
    ("AoE", "范围伤害", "wuwa", "meta"),
    ("Sustained DMG", "持续伤害", "wuwa", "meta"),
    ("Burst DMG", "爆发伤害", "wuwa", "meta"),
    ("Cleanse", "解控", "wuwa", "meta"),
    ("Elite Mob", "精英怪", "wuwa", "enemy"),
    ("Minion", "小兵", "wuwa", "enemy"),
    ("Boss Weakpoint", "BOSS弱点", "wuwa", "enemy"),
    ("Pull", "抽卡", "wuwa", "gacha"),
    ("Soft Pity", "小保底", "wuwa", "gacha"),
    ("Hard Pity", "大保底", "wuwa", "gacha"),
    ("Banner", "卡池", "wuwa", "gacha"),
    ("Limited Banner", "限定卡池", "wuwa", "gacha"),
    ("Standard Banner", "常驻卡池", "wuwa", "gacha"),
    ("Constellation", "命座", "wuwa", "gacha"),
    ("Duplicate Resonator", "重复共鸣者", "wuwa", "gacha"),
    ("Wish Count", "抽卡次数", "wuwa", "gacha"),
    ("Guarantee", "保底锁定", "wuwa", "gacha"),
    ("Tilt Harmony", "偏谐", "wuwa", "combat2"),
    ("Tilt Harmony Gauge", "偏谐值", "wuwa", "combat2"),
    ("Disharmony", "失谐", "wuwa", "combat2"),
    ("Harmony Break", "谐度破坏", "wuwa", "combat2"),
    ("Harmony Break Skill", "谐度破坏技", "wuwa", "combat2"),
    ("Tremor Harmony", "震谐", "wuwa", "combat2"),
    ("Gather Harmony", "集谐", "wuwa", "combat2"),
    ("Offset", "偏移", "wuwa", "combat2"),
    ("Interfere", "干涉", "wuwa", "combat2"),
    ("Tilt Harmony Efficiency", "偏谐值积累效率", "wuwa", "combat2"),
    ("Harmony Break Bonus", "谐度破坏增幅", "wuwa", "combat2"),
    ("Resonance Modal", "共鸣模态", "wuwa", "combat2"),
    ("Final Matrix", "终焉矩阵", "wuwa", "combat2"),
    ("Danger Assault", "险境强袭", "wuwa", "combat2"),
    ("Scientific Exploration Motorbike", "科考摩托", "wuwa", "combat2"),
    ("Void Damage", "虚湮", "wuwa", "combat2"),
    ("Frost Spread", "霜渐", "wuwa", "combat2"),
    ("Pull Effect", "牵引", "wuwa", "combat2"),
    ("Implosion", "聚爆", "wuwa", "combat2"),
    ("Harmony Response", "集谐响应", "wuwa", "combat2"),
    ("Hack Break Response", "骇破响应", "wuwa", "combat2"),
    ("HB", "谐度破坏", "wuwa", "combat2"),
    ("TH", "偏谐", "wuwa", "combat2"),
    ("Solaris", "索拉里斯", "wuwa", "location"),
    ("Huanglong", "瑝珑", "wuwa", "location"),
    ("Mingting", "明庭", "wuwa", "location"),
    ("Jinzhou", "今州", "wuwa", "location"),
    ("The Black Shores", "黑海岸", "wuwa", "location"),
    ("Rinascita", "黎那汐塔", "wuwa", "location"),
    ("Ragunna", "拉古那", "wuwa", "location"),
    ("Lahai-Roi", "拉海洛", "wuwa", "location"),
    ("Septimont", "七丘", "wuwa", "location"),
    ("New Federation", "新联邦", "wuwa", "faction"),
    ("The Fractsidus", "残星会", "wuwa", "faction"),
    ("Startorch Academy", "星炬学院", "wuwa", "faction"),
    ("Huaxu Academ", "华胥研究院", "wuwa", "faction"),
    ("Midnight Rangers", "夜归", "wuwa", "faction"),
    ("Mengzhou", "梦州", "wuwa", "location"),
    ("Dark Plain", "黯原", "wuwa", "location"),
    ("Xuanfang Boundary", "玄方地界", "wuwa", "location"),
    ("Xuanfang City", "玄方城", "wuwa", "location"),
    ("Xuanyou East Peak", "玄幽东岳", "wuwa", "location"),
    ("Fangqing West Peak", "方擎西峰", "wuwa", "location"),
    ("Luanyuan South Mound", "落渊南丘", "wuwa", "location"),
    ("Sunset Isle", "落日堤屿", "wuwa", "location"),
    ("Seal Ground", "封存地", "wuwa", "location"),
    ("Silent Cliff", "寂静断崖", "wuwa", "location"),
    ("Eternal Dark Plain", "恒黯之原", "wuwa", "location"),
    ("Avenulin", "阿维纽林", "wuwa", "location"),
    ("Beo Sea Area", "贝奥海域", "wuwa", "location"),
    ("Zhaoming Chamber of Commerce", "昭明商会", "wuwa", "faction"),
    ("Zhaoming", "昭明", "wuwa", "faction_alias"),
    ("Wangchuan Exhibition", "万川展会", "wuwa", "event"),
    ("Wangchuan", "万川", "wuwa", "event_alias"),
    ("Xuanqi Troops", "玄骑使", "wuwa", "faction"),
    ("Hidden Sea Covenant", "隐海修会", "wuwa", "faction"),
    ("Fool Troupe", "愚人剧团", "wuwa", "faction"),
    ("Mortari Family", "莫塔里家族", "wuwa", "faction"),
    ("Fesare Family", "翡萨烈家族", "wuwa", "faction"),
]

# Removed/renamed official spellings. Deleting these avoids contradictory
# matches while alias.json still normalizes common ASR variants.
deprecated_terms = [
    "Sui Sui",
    "Yangyang Xuanling",
    "Thermo",
    "Diffusion",
    "Oblivion",
    "Diffusion Rover",
    "Glacio Rover",
    "Thermo Rover",
    "Fusion Rover",
    "Aero Rover",
    "Oblivion Rover",
]
conn.executemany(
    "DELETE FROM glossary WHERE english=? AND game='wuwa'",
    [(term,) for term in deprecated_terms],
)

count = conn.executemany(
    'INSERT OR REPLACE INTO glossary (english, chinese, game, category) VALUES (?, ?, ?, ?)',
    terms
).rowcount
conn.commit()

total = conn.execute('SELECT COUNT(*) FROM glossary').fetchone()[0]
mode_label = "合并完成" if merge_mode else "导入完成"
print(f'{mode_label}: {total} 条术语')

cats = conn.execute('SELECT category, COUNT(*) as cnt FROM glossary GROUP BY category ORDER BY cnt DESC').fetchall()
for cat, cnt in cats:
    print(f'  {cat}: {cnt}')

conn.close()
